swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "0.0.1"
  title: Defect Prediction Swagger RESTful APIs
consumes:
  - "text/plain"
produces:
  - "application/json"

basePath: "/api/classification"

# Paths supported by the server application
paths:
  /classify:
    post:
      operationId: api.endpoints.classification.classify
      tags: 
        - "Detections"
      summary: "The defect classification"
      description: "Run defect detection on script"
      parameters:
        - in:  body
          name: script
          description: Run a new classification
          required: True
          schema:
            type: object
      responses:
        200:
          description: Success!
          schema:
            type: boolean