site_name: Receptor
repo_name: GitHub
repo_url: https://github.com/radon-h2020/radon-defect-prediction-api/
nav:
    - Getting Started: 
        - Quick Start: index.md
        - APIs: 
            - classification: api/classify
            - metrics: api/metrics
            - models: api/models
    - About: about.md
theme: readthedocs